dataviz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vizzes.urls')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vizzes/urls.py
from django.urls import path

from . import views

app_name = 'vizzes'
urlpatterns = [
    path('', views.IndexView, name='index'),
    path(r'datavizzes',views.VizListView.as_view(),name='VizList'),
    path(r'<int:pk>/', views.VizView.as_view(), name='viz'),
    path(r'<int:pk>/VizData', views.VizData, name='VizData'),
    path(r'about', views.aboutView, name='about')
    # path('ingest', views.IngestView, name='ingest'),
]

vizzes/models.py
from django.db import models

# Create your models here.

class Dataviz(models.Model):
    """Model definition for Dataviz."""
    D3_SCROLL = 'D3L'
    D3_STATIC = 'D3T'
    WORDS = 'WRD'
    TABLEAU = 'TBX'
    IMAGE = 'IMG'
    VIZ_TYPE_CHOICES = (
        (D3_SCROLL,'D3 w/ Scrollytelling'),
        (D3_STATIC,'Static D3'),
        (TABLEAU,'Embedded Tableau Workbook'),
        (IMAGE,'Image'),
        (WORDS,'Just Words')
    )
    viz_name = models.CharField(max_length=500,unique=True)
    viz_type  = models.CharField(max_length=3,choices=VIZ_TYPE_CHOICES,default=D3_STATIC)
    viz_verbose_name = models.CharField(max_length=500, default='---')
    date_added = models.DateTimeField('Date Added')
    viz_description = models.TextField(default='A brief Description of the Viz')
    viz_source = models.URLField(default='Data Source')
    viz_file = models.CharField(max_length=1000, default='Paste CDN URL or Tableau Workbook and sheet name (e.g., "workbook/sheetname") here')
    viz_thumb = models.URLField(default='https://cdn.jsdelivr.net/gh/jasparr77/d3/[Folder]/[PNG File]')
    author = models.CharField(max_length=25, default='')
    class Meta:
        """Meta definition for Dataviz."""

        verbose_name =  'Dataviz'
        verbose_name_plural =  'Datavizzes'

    def __str__(self):
        """Unicode representation of Dataviz."""
        return self.viz_name

vizzes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.views import generic
from django.urls import reverse
from django.apps import apps

# from .forms import IngestFileForm
# from .ingest import handle_file
from .models import Dataviz

import json

# Create your views here.

class VizListView(generic.ListView):
    template_name = 'vizzes/VizList.html'
    context_object_name = 'viz_list'
    def get_queryset(self):
        return Dataviz.objects.order_by('-date_added')[0:]
    
class VizView(generic.DetailView):
    model = Dataviz
    context_object_name = 'selected_dataviz'
    template_name = 'vizzes/detail.html'

def pickModel(viz_id_arg):
    modelname = str(Dataviz.objects.get(id=viz_id_arg))
    return apps.get_model('vizzes', modelname, require_ready=True)

def VizData(request, **args):
    viz_id_arg = args['pk']
    selected_model = pickModel(viz_id_arg)
    data = selected_model.objects.values()
    data = json.loads(json.dumps(data[0:len(data)]))
    return JsonResponse(data, safe=False)

def aboutView(request):
    template_name = 'vizzes/about.html'
    return render(request, template_name)

def IndexView(request):
    template_name = 'vizzes/index.html'
    return render(request, template_name)

vizzes/templates/vizzes/VizList.html
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Jasper Croome</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vizzes/style.css' %}">
<link rel="shortcut icon"type="image/png"href="{%static 'images/favicon.ico' %}">
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
<header class="header"id="headerVizDetail">
    <a href="{% url 'vizzes:index' %}"><div id="vizlistTitleBox"><p class="title"id="vizlistTitle">JC</p></div></a>
    <div class="linksbar">
        <p class ="headerlink"><a id="aboutLink" href="{% url 'vizzes:about' %}">About</a> | <b>Visualizations</b></p>
    </div>
</header>
<div class="vizlist-main">
    {% for dataviz in viz_list %}
        <div class="vizCard">
            <a class="vizLink" href="{% url 'vizzes:viz' dataviz.id %}">
                <img class="vizThumb" src="{{dataviz.viz_thumb}}">
                <div class="vizTitle">
                    <p>{{dataviz.viz_verbose_name}}</p>
                </div>
            </a>
        </div>
    {% endfor %} </ul> 
</div>
<div class ="footerContactBar">
    <div class="footercontactbutton empty"></div>
    <div class="footercontactbutton email"><a href="mailto:jjcroome@gmail.com"target="_blank"><img src="{% static 'images/email_PNG15.png' %}"></a></div>
    <div class="footercontactbutton linkedin"><a href="https://www.linkedin.com/in/jaspercroome/"target="_blank"><img src="{% static 'images/In-Blue-96.png' %}"alt="jasper's linkedin"></a></div>
    <div class="footercontactbutton twitter"><a href="https://twitter.com/CrasperJoome"target="_blank"><img src="{% static 'images/Twitter_Logo_Blue.png' %}"alt="jasper's twitter"></a></div>
    <div class="footercontactbutton github"><a href="https://github.com/Jasparr77"target="_blank"><img src="{% static 'images/GitHub-Mark-64px.png' %}"alt="jasper's GitHub"></a></div>
    <div class="footercontactbutton empty"></div>
</div>

vizzes/templates/vizzes/about.html
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Jasper Croome</title>
{% load static %}
<link rel="shortcut icon"type="image/png"href="{%static 'images/favicon.ico' %}">
<link rel="stylesheet" type="text/css" href="{% static 'vizzes/style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
<header class="header" id="headerAbout">
    <a href="{% url 'vizzes:index' %}"><div id="aboutTitleBox"><p class="title"id="aboutTitle">JC</p></div></a>
    <div class="linksbar">
        <p class="headerlink"><b>About</b> | <a id="vizlistLink"href="{% url 'vizzes:VizList' %}">Visualizations</a></p>
    </div>
</header>
<h4 class="vizDesc"></h4>
<div id="aboutbody">
    <div class="aboutsite">
        <h2>About This Site</h2>
            <p>This site is built using <a href="https://djangoproject.com/">Django</a>, and is hosted on <a href="https://www.heroku.com/">Heroku</a>. Source Code can be found on my <a href="https://github.com/Jasparr77/dataviz-project">GitHub Page</a>.
            <br>The pages are built using basic HTML / CSS, and the Data Visualizations are built using <a href="https://d3js.org/">D3</a> (and sometimes, <a href="https://github.com/russellgoldenberg/scrollama">Scrollama</a>).</p>
        <h2>About Jasper</h2>
            <p>I'm a Data Visualization Developer, with a passion for figuring out how things work and making life easier for others.
            <br>Outside of work, I enjoy cycling, roasting my own coffee beans, and exploring the outdoors with my daughter, wife & our Mini Aussie, Beau. 
            <br>Details around my career and skillset can be found below, but if you have more questions just reach out!</p>
        </div>
<div class ="footerContactBar">
    <div class="footercontactbutton empty"></div>
    <div class="footercontactbutton email"><a href="mailto:jjcroome@gmail.com"target="_blank"><img src="{% static 'images/email_PNG15.png' %}"></a></div>
    <div class="footercontactbutton linkedin"><a href="https://www.linkedin.com/in/jaspercroome/"target="_blank"><img src="{% static 'images/In-Blue-96.png' %}"alt="jasper's linkedin"></a></div>
    <div class="footercontactbutton twitter"><a href="https://twitter.com/CrasperJoome"target="_blank"><img src="{% static 'images/Twitter_Logo_Blue.png' %}"alt="jasper's twitter"></a></div>
    <div class="footercontactbutton github"><a href="https://github.com/Jasparr77"target="_blank"><img src="{% static 'images/GitHub-Mark-64px.png' %}"alt="jasper's GitHub"></a></div>
    <div class="footercontactbutton empty"></div>
</div>
<div class="footer">
     <script src="{% static 'vizzes/js/d3.v4.min.js' %}"></script>
     <script src="{% static 'vizzes/js/resize.js' %}"></script>
     <script src="{% static 'vizzes/js/about_timeline.js' %}"></script>
</div>

vizzes/templates/vizzes/detail.html
<!DOCTYPE html>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>VizLab</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vizzes/style.css' %}" />
<link
  rel="shortcut icon"
  type="image/png"
  href="{%static 'images/favicon.ico' %}"
/>
<link
  href="https://fonts.googleapis.com/css?family=Quicksand"
  rel="stylesheet"
/>
<header class="header" id="headerVizDetail">
  <a href="{% url 'vizzes:index' %}"
    ><div id="vizdetailTitleBox">
      <p class="title" id="vizdetailTitle">JC</p>
    </div></a
  >
  <p class="vizVerbose">{{ selected_dataviz.viz_verbose_name }}</p>
  <div class="linksbar">
    <a class="headerlink" href="{% url 'vizzes:VizList' %}">back</a>
  </div>
</header>
<h4 class="vizDesc">{{ selected_dataviz.viz_description }}</h4>
{% if selected_dataviz.viz_type == 'D3L' %}
<section id="scroll">
  <div class="scroll__graphic sticky"><svg class="chart"></svg></div>
  <div class="scroll__text"></div>
</section>
<div class="footer">
  <script src="{% static 'vizzes/js/d3.v5.min.js' %}"></script>
  <script src="{% static 'vizzes/js/resize.js' %}"></script>
  <script src="{% static 'vizzes/js/intersection-observer.0-5.js' %}"></script>
  <script src="https://unpkg.com/scrollama"></script>
  <script src="https://russellgoldenberg.github.io/scrollama/stickyfill.min.js"></script>
  <script src="{% static 'vizzes/js/d3.topojson.v2.min.js' %}"></script>
  <script type="text/javascript" src="{{ selected_dataviz.viz_file }}"></script>
  <p>
    Added to DB {{ selected_dataviz.date_added }}
    <a href="{{ selected_dataviz.viz_source }}" target="_blank">data source</a>
  </p>
</div>
{% elif selected_dataviz.viz_type == 'D3T' %}
<div id="staticBody"></div>
<div class="footer">
  <script src="{% static 'vizzes/js/d3.v5.min.js' %}"></script>
  <script src="{% static 'vizzes/js/resize.js' %}"></script>
  <script src="{% static 'vizzes/js/d3.topojson.v2.min.js' %}"></script>
  <script type="text/javascript" src="{{ selected_dataviz.viz_file }}"></script>
  <p>
    Added to DB {{ selected_dataviz.date_added }}
    <a href="{{ selected_dataviz.viz_source }}" target="_blank">data source</a>
  </p>
</div>
{% elif selected_dataviz.viz_type == 'TBX' %}
<div class="tableauPlaceholder">
  <object class="tableauViz">
    <param name="host_url" value="https%3A%2F%2F10ax.online.tableau.com%2F" />
    <param name="embed_code_version" value="3" />
    <param name="site_root" value="&#47;t&#47;jasperdevdev358361" />
    <param name="name" value="{{ selected_dataviz.viz_file }}" /><param
      name="tabs"
      value="no"
    />
    <param name="toolbar" value="yes" />
    <param name="showAppBanner" value="false" />
    <param name="filter" value="iframeSizedToWindow=true" />
  </object>
</div>
<div class="footer">
  <script
    type="text/javascript"
    src="https://10ax.online.tableau.com/javascripts/api/viz_v1.js"
  ></script>
  <script src="{% static 'vizzes/js/d3.v4.min.js' %}"></script>
  <script src="{% static 'vizzes/js/resize.js' %}"></script>
  <p>
    Added to DB {{ selected_dataviz.date_added }}
    <a href="{{ selected_dataviz.viz_source }}" target="_blank">data source</a>
  </p>
</div>
{% elif selected_dataviz.viz_type == 'IMG' %}
<div class="pictureBox"><img src="{{ selected_dataviz.viz_file }}" /></div>
<div class="footer">
  <script src="{% static 'vizzes/js/d3.v4.min.js' %}"></script>
  <script src="{% static 'vizzes/js/resize.js' %}"></script>
  <p>
    Added to DB {{ selected_dataviz.date_added }}
    <a href="{{ selected_dataviz.viz_source }}" target="_blank">data source</a>
  </p>
</div>
{% elif selected_dataviz.viz_type == 'WRD' %}
<div class="wordBox"><p src="{{ selected_dataviz.viz_file }}"></p></div>
<div class="footer">
  <script src="{% static 'vizzes/js/d3.v4.min.js' %}"></script>
  <script src="{% static 'vizzes/js/resize.js' %}"></script>
  <p>
    Added to DB {{ selected_dataviz.date_added }}
    <a href="{{ selected_dataviz.viz_source }}" target="_blank">data source</a>
  </p>
</div>
{% endif %}

vizzes/templates/vizzes/index.html
<!DOCTYPE html>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Jasper Croome</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vizzes/style.css' %}" />
<link
  rel="shortcut icon"
  type="image/png"
  href="{%static 'images/favicon.ico' %}"
/>
<link
  href="https://fonts.googleapis.com/css?family=Quicksand"
  rel="stylesheet"
/>
<header class="header" id="headerIndex">
  <div id="indexTitleBox"><p class="title" id="indexTitle">JC</p></div>
  <div class="linksbar">
    <p class="headerlink">
      <a id="aboutLink" href="{% url 'vizzes:about' %}" underline="#2980b9"
        >About</a
      >
      | <a id="vizlistLink" href="{% url 'vizzes:VizList' %}">Visualizations</a>
    </p>
  </div>
</header>
<div id="indexintro">
  <h1>Hi, I'm Jasper Croome.</h1>
  <p>
    I'm an Information Designer with a passion for
    <a href="{% url 'vizzes:VizList' %}"
      ><button id="indexCTA">Data Visualization</button></a
    >.
  </p>
</div>
<div class="footerContactBar">
  <div class="footercontactbutton empty"></div>
  <div class="contactbutton email">
    <a href="mailto:jjcroome@gmail.com" target="_blank"
      ><img src="{% static 'images/email_PNG15.png' %}"
    /></a>
  </div>
  <div class="contactbutton linkedin">
    <a href="https://www.linkedin.com/in/jaspercroome/" target="_blank"
      ><img src="{% static 'images/In-Blue-96.png' %}" alt="jasper's linkedin"
    /></a>
  </div>
  <div class="contactbutton twitter">
    <a href="https://twitter.com/CrasperJoome" target="_blank"
      ><img
        src="{% static 'images/Twitter_Logo_Blue.png' %}"
        alt="jasper's twitter"
    /></a>
  </div>
  <div class="contactbutton github">
    <a href="https://github.com/Jasparr77" target="_blank"
      ><img
        src="{% static 'images/GitHub-Mark-64px.png' %}"
        alt="jasper's GitHub"
    /></a>
  </div>
  <div class="footercontactbutton empty"></div>
</div>

vizzes/templates/vizzes/ingest.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dataviz/style.css' %}">

<form method="POST">
    {{ form }}
    <input type="submit" Value="Go get it">
</form>